### ISSUE TITLE
Survnip + glmnet/coxnet?

### ISSUE THREAD

**Issue by dvdsb** [EmilHvitfeldt/survnip#9]
Dear Emil, I´m new to github so I apologize in advance. I wonder if Survnip can be used for regularized Cox regression (LASSO/rigde/Elastic Net)? Kind regards David

**Comment by EmilHvitfeldt** [comment]
Hello David,

It is not ready yet, but it will be available :)

**Comment by EmilHvitfeldt** [comment]
Hello @dvdsb, `survnip` should now be able to do regualized Cox regression.
